# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_hellosayer.ipynb.

# %% auto 0
__all__ = ['say_hello']

# %% ../nbs/00_hellosayer.ipynb 3
def say_hello(name):
    """This function says hello
    
    name: (string) The person we are greeting.
    """
    return f"Hello {name}! How are you?"
